### ISSUE TITLE
CDN静态资源不稳定

### ISSUE THREAD

**Issue by zy7y** [codematrixer/ui-viewer#1]
index.html文件中，使用cdn加载js/css文件，概率出现失败，资源下载到本地可能更合适

**Comment by codematrixer** [comment]
> index.html文件中，使用cdn加载js/css文件，概率出现失败，资源下载到本地可能更合适

好的，感谢反馈，欢迎点Star

**Comment by codematrixer** [comment]
已发布  https://github.com/codematrixer/ui-viewer/releases/tag/1.0.3
