### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by zy7y** [codematrixer/ui-viewer#2]
- 设备截图视口可放大缩小（不放大看着有点糊）
- 网页title名称 修改为项目名称更好
- 左侧树、label 显示 _type  + resourceId  两个字段更清晰

**Comment by codematrixer** [comment]
收到，适配中

**Comment by codematrixer** [comment]
三个问题都已修复 https://github.com/codematrixer/ui-viewer/releases/tag/1.1.3
